baseurl = "https://blog.rex.wf"
languageCode = "en-us"
theme = "terminal"

enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[pagination]
  pagerSize = 5

[params]
    contentTypeName = "posts"
    centerTheme = true
    autoCover = true
    dateFormat = "Jan 2, 2006"
    showLastUpdated = false
    
    description = "rex's blog"
    keywords = ["blog", "tech", "programming", "ctf", "writeups"]
    author = "rex"
    
    enableOpenGraph = true
    images = ["/og-image.png"]
    
    enableTwitterCards = true
    twitterSite = "@rexmkv"
    twitterCreator = "@rexmkv"
    twitterImage = "/og-image.png"
    
    enableCanonicalLinks = true
    enableSchema = true
    schemaType = "Person"
    googleSiteVerification = ""

    [params.sitemap]
        changefreq = "weekly"
        priority = 0.5
        filename = "sitemap.xml"

[outputs]
    home = ["HTML", "RSS", "JSON", "SITEMAP"]

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[languages]
  [languages.en]
    languageName = "English"
    title = "blog"

    [languages.en.params]
      subtitle = "i have no idea what i'm doing"
      owner = "rex"
      keywords = "blog, tech, programming, personal"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "rex"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"